import React, { CSSProperties } from 'react';
import { EventHandler } from "react-free-draggable";
import { DndProps, DndBaseProps, DndParams } from "./utils/types";
export default function BuildDndSortable(): {
    new (props: DndProps): {
        sortArea: any;
        dragged: any;
        cloneDragged: any;
        over: HTMLElement | undefined;
        lastDisplay: CSSProperties['display'];
        componentDidMount(): void;
        componentDidUpdate(prevProps: DndProps): void;
        componentWillUnmount(): void;
        getOptions: (options: DndProps['options']) => DndProps['options'];
        initManagerData: (sortArea: any) => void;
        onStart: EventHandler;
        onEnd: EventHandler;
        onDragEnd: (e: any) => void;
        reset: () => void;
        handleDragOverClass: (params: {
            draggedIndex: number;
            newOverIndex: number;
            oldOverIndex: number;
            newOver: HTMLElement;
            oldOver?: HTMLElement;
            props: DndBaseProps;
        }) => void;
        onDragStart: (e: any) => void;
        onTouchMoveStart: EventHandler;
        moveStartHandle: (e: any, currentTarget?: any) => void;
        moveHandle: EventHandler;
        onTouchMove: EventHandler;
        onDragOver: (e: any) => void;
        sortInSameArea: (params: DndParams) => void;
        addNewOver: (params: DndParams) => void;
        setDropEndChild: (params: DndParams) => void;
        renderChild(child: any): JSX.Element;
        render(): JSX.Element;
        context: any;
        setState<K extends never>(state: {} | ((prevState: Readonly<{}>, props: Readonly<DndProps>) => {} | Pick<{}, K> | null) | Pick<{}, K> | null, callback?: (() => void) | undefined): void;
        forceUpdate(callback?: (() => void) | undefined): void;
        readonly props: Readonly<DndProps> & Readonly<{
            children?: React.ReactNode;
        }>;
        state: Readonly<{}>;
        refs: {
            [key: string]: React.ReactInstance;
        };
        shouldComponentUpdate?(nextProps: Readonly<DndProps>, nextState: Readonly<{}>, nextContext: any): boolean;
        componentDidCatch?(error: Error, errorInfo: React.ErrorInfo): void;
        getSnapshotBeforeUpdate?(prevProps: Readonly<DndProps>, prevState: Readonly<{}>): any;
        componentWillMount?(): void;
        UNSAFE_componentWillMount?(): void;
        componentWillReceiveProps?(nextProps: Readonly<DndProps>, nextContext: any): void;
        UNSAFE_componentWillReceiveProps?(nextProps: Readonly<DndProps>, nextContext: any): void;
        componentWillUpdate?(nextProps: Readonly<DndProps>, nextState: Readonly<{}>, nextContext: any): void;
        UNSAFE_componentWillUpdate?(nextProps: Readonly<DndProps>, nextState: Readonly<{}>, nextContext: any): void;
    };
    contextType?: React.Context<any> | undefined;
};
